In [1]:
import pandas as pd
import sqlite3

sheets = pd.read_excel("/content/northwind_data.xlsx", sheet_name=None)

for name, df in sheets.items():
    print(name, df.shape)

conn = sqlite3.connect(":memory:")
for name, df in sheets.items():
    df.to_sql(name, conn, index=False, if_exists="replace")

def run(query):
    return pd.read_sql_query(query, conn)

customers (91, 11)
products (77, 10)
orders (830, 14)
order_details (2155, 5)
employees (9, 18)
categories (8, 4)
suppliers (29, 12)
shippers (6, 3)

In [2]:
sheets["customers"].head()

,customer_id,company_name,contact_name,contact_title,address,city,region,postal_code,country,phone,fax
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,NaN,12209,Germany,030-0074321,030-0076545
1,ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,Avda. de la Constitución 2222,México D.F.,NaN,05021,Mexico,(5) 555-4729,(5) 555-3745
2,ANTON,Antonio Moreno Taquería,Antonio Moreno,Owner,Mataderos 2312,México D.F.,NaN,05023,Mexico,(5) 555-3932,NaN
3,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,NaN,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
4,BERGS,Berglunds snabbköp,Christina Berglund,Order Administrator,Berguvsvägen 8,Luleå,NaN,S-958 22,Sweden,0921-12 34 65,0921-12 34 67

In [3]:
run("SELECT * FROM customers")

,customer_id,company_name,contact_name,contact_title,address,city,region,postal_code,country,phone,fax
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,None,12209,Germany,030-0074321,030-0076545
1,ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,Avda. de la Constitución 2222,México D.F.,None,05021,Mexico,(5) 555-4729,(5) 555-3745
2,ANTON,Antonio Moreno Taquería,Antonio Moreno,Owner,Mataderos 2312,México D.F.,None,05023,Mexico,(5) 555-3932,None
3,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,None,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
4,BERGS,Berglunds snabbköp,Christina Berglund,Order Administrator,Berguvsvägen 8,Luleå,None,S-958 22,Sweden,0921-12 34 65,0921-12 34 67
...,...,...,...,...,...,...,...,...,...,...,...
86,WARTH,Wartian Herkku,Pirkko Koskitalo,Accounting Manager,Torikatu 38,Oulu,None,90110,Finland,981-443655,981-443655
87,WELLI,Wellington Importadora,Paula Parente,Sales Manager,"Rua do Mercado, 12",Resende,SP,08737-363,Brazil,(14) 555-8122,None
88,WHITC,White Clover Markets,Karl Jablonski,Owner,305 - 14th Ave. S. Suite 3B,Seattle,WA,98128,USA,(206) 555-4112,(206) 555-4115
89,WILMK,Wilman Kala,Matti Karttunen,Owner/Marketing Assistant,Keskuskatu 45,Helsinki,None,21240,Finland,90-224 8858,90-224 8858
90,WOLZA,Wolski Zajazd,Zbyszek Piestrzeniewicz,Owner,ul. Filtrowa 68,Warszawa,None,01-012,Poland,(26) 642-7012,(26) 642-7012

In [4]:
run("SELECT company_name, country FROM customers")

                          company_name  country
0                  Alfreds Futterkiste  Germany
1   Ana Trujillo Emparedados y helados   Mexico
2              Antonio Moreno Taquería   Mexico
3                      Around the Horn       UK
4                   Berglunds snabbköp   Sweden
..                                 ...      ...
86                      Wartian Herkku  Finland
87              Wellington Importadora   Brazil
88                White Clover Markets      USA
89                         Wilman Kala  Finland
90                      Wolski  Zajazd   Poland

[91 rows x 2 columns]

In [5]:
run("SELECT * FROM customers WHERE country = 'Germany'")

,customer_id,company_name,contact_name,contact_title,address,city,region,postal_code,country,phone,fax
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,None,12209,Germany,030-0074321,030-0076545
1,BLAUS,Blauer See Delikatessen,Hanna Moos,Sales Representative,Forsterstr. 57,Mannheim,None,68306,Germany,0621-08460,0621-08924
2,DRACD,Drachenblut Delikatessen,Sven Ottlieb,Order Administrator,Walserweg 21,Aachen,None,52066,Germany,0241-039123,0241-059428
3,FRANK,Frankenversand,Peter Franken,Marketing Manager,Berliner Platz 43,München,None,80805,Germany,089-0877310,089-0877451
4,KOENE,Königlich Essen,Philip Cramer,Sales Associate,Maubelstr. 90,Brandenburg,None,14776,Germany,0555-09876,None
5,LEHMS,Lehmanns Marktstand,Renate Messner,Sales Representative,Magazinweg 7,Frankfurt a.M.,None,60528,Germany,069-0245984,069-0245874
6,MORGK,Morgenstern Gesundkost,Alexander Feuer,Marketing Assistant,Heerstr. 22,Leipzig,None,04179,Germany,0342-023176,None
7,OTTIK,Ottilies Käseladen,Henriette Pfalzheim,Owner,Mehrheimerstr. 369,Köln,None,50739,Germany,0221-0644327,0221-0765721
8,QUICK,QUICK-Stop,Horst Kloss,Accounting Manager,Taucherstraße 10,Cunewalde,None,01307,Germany,0372-035188,None
9,TOMSP,Toms Spezialitäten,Karin Josephs,Marketing Manager,Luisenstr. 48,Münster,None,44087,Germany,0251-031259,0251-035695
10,WANDK,Die Wandernde Kuh,Rita Müller,Sales Representative,Adenauerallee 900,Stuttgart,None,70563,Germany,0711-020361,0711-035428

In [6]:
run("SELECT product_name, unit_price FROM products WHERE unit_price > 50")

              product_name  unit_price
0          Mishi Kobe Niku   97.000000
1         Carnarvon Tigers   62.500000
2   Sir Rodney's Marmalade   81.000000
3  Thüringer Rostbratwurst  123.790001
4            Côte de Blaye  263.500000
5    Manjimup Dried Apples   53.000000
6     Raclette Courdavault   55.000000

In [7]:
run("SELECT product_name, unit_price FROM products ORDER BY unit_price DESC")

               product_name  unit_price
0             Côte de Blaye  263.500000
1   Thüringer Rostbratwurst  123.790001
2           Mishi Kobe Niku   97.000000
3    Sir Rodney's Marmalade   81.000000
4          Carnarvon Tigers   62.500000
..                      ...         ...
72                Tourtière    7.450000
73                 Filo Mix    7.000000
74                    Konbu    6.000000
75       Guaraná Fantástica    4.500000
76                  Geitost    2.500000

[77 rows x 2 columns]

In [8]:
run("SELECT company_name, city FROM customers ORDER BY company_name ASC")

                          company_name         city
0                  Alfreds Futterkiste       Berlin
1   Ana Trujillo Emparedados y helados  México D.F.
2              Antonio Moreno Taquería  México D.F.
3                      Around the Horn       London
4                        B's Beverages       London
..                                 ...          ...
86                      Wartian Herkku         Oulu
87              Wellington Importadora      Resende
88                White Clover Markets      Seattle
89                         Wilman Kala     Helsinki
90                      Wolski  Zajazd     Warszawa

[91 rows x 2 columns]

In [9]:
run("SELECT order_id, order_date FROM orders WHERE strftime('%Y', order_date) = '1997'")

     order_id  order_date
0       10400  1997-01-01
1       10401  1997-01-01
2       10402  1997-01-02
3       10403  1997-01-03
4       10404  1997-01-03
..        ...         ...
403     10803  1997-12-30
404     10804  1997-12-30
405     10805  1997-12-30
406     10806  1997-12-31
407     10807  1997-12-31

[408 rows x 2 columns]

In [10]:
run("SELECT product_name, unit_price FROM products ORDER BY unit_price DESC LIMIT 5")

              product_name  unit_price
0            Côte de Blaye  263.500000
1  Thüringer Rostbratwurst  123.790001
2          Mishi Kobe Niku   97.000000
3   Sir Rodney's Marmalade   81.000000
4         Carnarvon Tigers   62.500000

In [11]:
run("SELECT company_name, country FROM customers WHERE country IN ('USA', 'UK')")

                         company_name country
0                     Around the Horn      UK
1                       B's Beverages      UK
2               Consolidated Holdings      UK
3                  Eastern Connection      UK
4             Great Lakes Food Market     USA
5          Hungry Coyote Import Store     USA
6                      Island Trading      UK
7                Lazy K Kountry Store     USA
8                   Let's Stop N Shop     USA
9            Lonesome Pine Restaurant     USA
10                        North/South      UK
11             Old World Delicatessen     USA
12         Rattlesnake Canyon Grocery     USA
13                 Save-a-lot Markets     USA
14                 Seven Seas Imports      UK
15              Split Rail Beer & Ale     USA
16                     The Big Cheese     USA
17                    The Cracker Box     USA
18  Trail's Head Gourmet Provisioners     USA
19               White Clover Markets     USA

In [12]:
run("SELECT first_name, last_name, city FROM employees WHERE city = 'London'")

  first_name  last_name    city
0     Steven   Buchanan  London
1    Michael     Suyama  London
2     Robert       King  London
3       Anne  Dodsworth  London

**Conclusion**

In this task, I wrote and ran basic SQL queries on the Northwind dataset. I loaded the dataset from Excel into Google Colab, converted it into a SQLite database, and executed 10 queries.

**What I did:**

Used SELECT to retrieve data from the customers, products, and employees tables.
Used WHERE to filter data, such as customers from Germany, products priced above 50, customers from the USA or UK, and employees based in London.
Used ORDER BY to sort results, such as products by price (high to low) and companies alphabetically (A-Z).
Used LIMIT to fetch the top 5 most expensive products.

**What I learned:**

How to select, filter, and sort data using SQL.
How to use the IN operator and LIMIT clause.
How to write clean, readable queries by capitalizing keywords and placing each clause on a new line.
How to work with real business data such as customers, orders, and products.